### ISSUE TITLE
New PHub destroys download_urls?

### ISSUE THREAD

**Issue by xXMrrpgXx** [JustalK/PORNHUB-API#43]
### Hi its me again, needing your download_urls method 😃. 

This time i have a problem with video format, its not a bug or anything. 
Before im pretty sure you recieved a .mp4 file when downloading urls but now you get this weird .m3u8 file. I've read about it and its like a playlist file, but i cant convert it to mp4 or similar. 

The url it self has a .mp4 file, if you cut all the other options like the .m3u8, depending on the video you get different errors but all of them involve permission (Having to register) which sucks. 

EDIT: Also, sometimes i get 403 errors :(

My point, is there a way around it?

Thank you, xXMrrpgXx

**Comment by JustalK** [comment]
Hello xXMrrpgXx,
Thank you for your feedback !

The way my download works is as follow :
- I get all the part of the download URL from the javascript
- I build back the different download URL I manage to get
- I check if the URL is valid

The problem is it seems at first view that PH create fake link inside for avoiding this kind of downloader.
I need to search a bit more.

Can you give me an URL where you get that error ?
It does not happen everywhere, so it's hard to debug.

Thank you !

**Comment by xXMrrpgXx** [comment]
Thanks for your answer! 
Im really sorry for the late response.

Here are some examples: 
`URL: http://pornhub.com/view_video.php?viewkey=ph5eef378b83388`
`1080p download link (they're all the same type): https://ev-h.phncdn.com/hls/videos/202006/21/325678372/201218_1706_1080P_8000K_325678372.mp4/master.m3u8?validfrom=1611072724&validto=1611079924&hdl=-1&hash=%2BvzOghjkqd2DKvOz3NvJjAmR90Y%3D`
![image](https://user-images.githubusercontent.com/57962493/105069404-2badf080-5a82-11eb-81f0-f718045562b9.png)

Another one:
`URL (With spain subdomain): https://es.pornhub.com/view_video.php?viewkey=1767297513`
`720p download link: https://ev-h.phncdn.com/hls/videos/201504/15/47620541/,191218_0700_720P_4000K,191218_0700_480P_2000K,191218_0700_240P_400K,_47620541.mp4.urlset/master.m3u8?validfrom=1611073018&validto=1611080218&hdl=-1&hash=Y5UsXSfoqBBKVwUQVlmyHMLcavo=`
![image](https://user-images.githubusercontent.com/57962493/105069902-dd4d2180-5a82-11eb-8caf-4546dbd1d943.png)
